services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-blog
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mysql
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghostdb
    volumes:
      - ./content:/var/lib/ghost/content

  mysql:
    image: mysql:8
    container_name: ghost-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: